menubar: false
branding: false
force_br_newlines : true
force_p_newlines : false
# forced_root_block : "p"
forced_root_block : "p"
invalid_elements: "div"
toolbar:
  - bold italic underline fontsizeselect bullist numlist subscript superscript forecolor backcolor
plugins:
  - link
  - textcolor
  - lists
  - colorpicker
  - textcolor
